### ISSUE TITLE
file cannot open on ios

### ISSUE THREAD

**Issue by kapiltandukar** [JideGuru/epub_viewer#43]
Issue / Feature - 
Platform (android, iOS or both) - ios
Crash / Error - 
<img width="769" alt="Screen Shot 2020-10-13 at 10 05 01" src="https://user-images.githubusercontent.com/3233200/95815032-9345f880-0d3b-11eb-80de-a32c720e7e2b.png">

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-10-13 at 10 02 43](https://user-images.githubusercontent.com/3233200/95814975-71e50c80-0d3b-11eb-9cb3-cc10fe09b5e7.png)

Steps to reproduce / Describe in detail -

**Comment by kuntadynithesh** [comment]
Looks like this is a problem with Epub file , not application

**Comment by kapiltandukar** [comment]
@kuntadynithesh this build is from example epub_viewer and it's work on android. only issue on ios.

**Comment by JideGuru** [comment]
@kapiltandukar This is an issue from the plugin and I'm working on fixing it

**Comment by kapiltandukar** [comment]
@JideGuru please try to solve this issue as soon as possible. i'm having big trouble right now. hope you will understand it. Thank you.

**Comment by kapiltandukar** [comment]
@JideGuru  is there any good news. waiting your response. 👍

**Comment by JideGuru** [comment]
@kapiltandukar none yet.
Still working on it as it requires a lot of work

**Comment by hvmien** [comment]
I think reason is in function loadHTMLString on file FolioReaderPage.swift from line 156 .
I fixed it.
```if title.contains(\"xhtml") {
              ...
                webView?.loadFileURL(URL(fileURLWithPath: filePath), allowingReadAccessTo:URL(fileURLWithPath: baseURL.path.deletingLastPathComponent))
            }else {
                try! tempHtmlContent.write(toFile: filePath, atomically: true, encoding: String.Encoding.utf8)
                webView?.loadHTMLString(tempHtmlContent, baseURL: baseURL)
            }
```

**Comment by 312654929** [comment]
> I think reason is in function loadHTMLString on file FolioReaderPage.swift from line 156 .
> I fixed it.
> 
> ```
>               ...
>                 webView?.loadFileURL(URL(fileURLWithPath: filePath), allowingReadAccessTo:URL(fileURLWithPath: baseURL.path.deletingLastPathComponent))
>             }else {
>                 try! tempHtmlContent.write(toFile: filePath, atomically: true, encoding: String.Encoding.utf8)
>                 webView?.loadHTMLString(tempHtmlContent, baseURL: baseURL)
>             }
> ```
It has been modified or not solved. The error eoub content is an XML file
